[WIP] Develop DeduplicateDocuments filter
WorksApplications/uzushio pull request #25
Opened 2023-09-21 05:32 UTC by otakumesi

Add a per-document deduplication filter.

[TODO]
- [x] Develop draft implementation
- [ ] Compute document stats and think about threshold
- [ ] Implements production code
- [ ] Add Spec

2023-09-21 05:46 UTC, otakumesi commented
https://github.com/WorksApplications/uzushio/issues/9#issue-1889666288

2023-09-21 10:34 UTC, eiennohito requested changes

2023-09-21 10:34 UTC, eiennohito commented on lib/src/main/scala/com/worksap/nlp/uzushio/lib/filters/DeduplicateDocuments.scala
> +  def computeNearDuplicateTextRatio(doc: Document): Float = {
指標はいいと思います！

2023-09-21 10:34 UTC, eiennohito commented on lib/src/main/scala/com/worksap/nlp/uzushio/lib/filters/DeduplicateDocuments.scala
> +    nearDuplicateTextRatio >= thresholdProb
この条件は正しくないと思います。

文書の9割は１回以上コーパスで出てきたと100回以上出てきたことを同じ確率にするのは正しくないと思います。

2023-09-21 12:40 UTC, otakumesi commented on lib/src/main/scala/com/worksap/nlp/uzushio/lib/filters/DeduplicateDocuments.scala
> +    nearDuplicateTextRatio >= thresholdProb
なるほど、確かに現在は現在は2回以上の重複を同じ扱いにして、その重複しているテキストの割合を計算してました。
そうなると、例えばnearFreqで重みを付けて重み付きのratioを計算したり、平均nearFreqなどでthresholdを調整してみるとかをした方が良いということでしょうか。

2023-09-21 12:58 UTC, otakumesi commented on lib/src/main/scala/com/worksap/nlp/uzushio/lib/filters/DeduplicateDocuments.scala
> +    nearDuplicateTextRatio >= thresholdProb
擬似コードですが、例えばこんな感じの実装はどうでしょう。
```
weights = 1 / (ln(nearFreqList)+1)
ParagrahLengthsOverOne = [ParagraphLength if nearFreq > 1 else 0]
ratio = weightedSum(ParagrahLengthsOverOne, weights)  / weightedSum(paragraphLengths, weights)

```

2023-09-21 13:36 UTC, otakumesi commented on lib/src/main/scala/com/worksap/nlp/uzushio/lib/filters/DeduplicateDocuments.scala
> +    nearDuplicateTextRatio >= thresholdProb
ただ、平均的なFreqが大きいほどthresholdProbが小さくなるように実装した方が自然かもしれませんね。
となると、乱数の分布パラメータに平均Freqをいれてあげるとかですかね。

2023-09-22 04:57 UTC, otakumesi commented on lib/src/main/scala/com/worksap/nlp/uzushio/lib/filters/DeduplicateDocuments.scala
> +    nearDuplicateTextRatio >= thresholdProb
https://github.com/WorksApplications/uzushio/pull/25/files#diff-b97c0389f5b19a25a0e0b320169e9d0e137b9e24fc420835827209d4e2ceda7bR24-R47
反映させてみました。

Freqが大きい段落があるほど、1に近づくという指標です。

2023-09-22 08:13 UTC, eiennohito commented on lib/src/main/scala/com/worksap/nlp/uzushio/lib/filters/DeduplicateDocuments.scala
> +    nearDuplicateTextRatio >= thresholdProb
結果的に重複ドキュメントは何個残りそうですか？

2023-09-25 05:56 UTC, otakumesi commented on lib/src/main/scala/com/worksap/nlp/uzushio/lib/filters/DeduplicateDocuments.scala
> +    nearDuplicateTextRatio >= thresholdProb
@eiennohito 軽く確認をしてみたところ、こんな感じでした。
* (フィルタ前) -> (フィルタ後）
* 244 -> 228 
* 276 -> 266
* 267 -> 229
* 239 -> 228

2023-09-25 12:52 UTC, otakumesi commented on lib/src/main/scala/com/worksap/nlp/uzushio/lib/filters/DeduplicateDocuments.scala
> +    nearDuplicateTextRatio >= thresholdProb
mu=0.1、sd=0.1の正規乱数で本指標をフィルタしたところ、

- 244 -> 137
- 276 -> 147
- 267 -> 139
- 239 -> 124

だいたい半分くらい減りましたね。
フィルタできたドキュメントをうまく抽出できないか見てみます。

2023-09-27 00:11 UTC, eiennohito commented
実験のために現時点でマージしたいのですが、どうしましょうか？

2023-09-27 00:44 UTC, otakumesi commented
@eiennohito もうマージしていただいても問題ないです〜。

2023-09-27 01:05 UTC, merged